services:
  db:
    image: postgres:15
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myapp_development
    ports:
      - "5432:5432"

  web:
    image: ruby:3.4
    volumes:
      - ./project:/myapp
      - bundle_data:/myapp/vendor/bundle
    working_dir: /myapp
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
    command: /bin/sh -c "bundle config set path vendor/bundle && bundle install && rm -f tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0 -p 3000"
    depends_on:
      - db
  
  front:
    image: node:20
    volumes:
      - ./front:/app
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3000
    working_dir: /app
    command: /bin/sh -c "npm install && npm run dev"

volumes:
  db_data:
  bundle_data:
